title: SYBS
author:
  name: Paolo Brasolin
  email: paolo.brasolin+sybs@gmail.com
description:
# baseurl: "/sybs"
# url: "http://paolobrasolin.github.io"

permalink: pretty

feedless: true

sass:
  style: compressed

# gems:
  # - jekyll-feed
  # - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

EMPTY_STRING: []

